//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AceTuitionPaymentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_addon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_addon()
        {
            this.tb_receipt_addon = new HashSet<tb_receipt_addon>();
        }
    
        public int addon_id { get; set; }
        public string addon_english_name { get; set; }
        public string addon_chinese_name { get; set; }
        public string addon_recursive { get; set; }
        public decimal addon_value { get; set; }
        public string addon_status { get; set; }
        public string child_ic { get; set; }
    
        public virtual tb_child tb_child { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_receipt_addon> tb_receipt_addon { get; set; }
    }
}
