//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AceTuitionPaymentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_child_package
    {
        public int child_package { get; set; }
        public int package_id { get; set; }
        public string child_ic { get; set; }
    
        public virtual tb_child tb_child { get; set; }
        public virtual tb_package tb_package { get; set; }
    }
}
