//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AceTuitionPaymentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_discount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_discount()
        {
            this.tb_receipt_discount = new HashSet<tb_receipt_discount>();
        }
    
        public int discount_id { get; set; }
        public string discount_english_name { get; set; }
        public string discount_chinese_name { get; set; }
        public string discount_recursive { get; set; }
        public decimal discount_value { get; set; }
        public string discount_status { get; set; }
        public string child_ic { get; set; }
    
        public virtual tb_child tb_child { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_receipt_discount> tb_receipt_discount { get; set; }
    }
}
