//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AceTuitionPaymentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_parent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_parent()
        {
            this.tb_balance = new HashSet<tb_balance>();
            this.tb_payment = new HashSet<tb_payment>();
        }
    
        public string parent_ic { get; set; }
        public string parent_password { get; set; }
        public string parent_name { get; set; }
        public string parent_address { get; set; }
        public string parent_phone { get; set; }
        public string parent_status { get; set; }

        public string parent_new_password { get; set; }
        public string parent_confirm_password { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_balance> tb_balance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_payment> tb_payment { get; set; }
    }
}
