//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AceTuitionPaymentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_payment_file
    {
        public int payment_file_id { get; set; }
        public int payment_id { get; set; }
        public string payment_file { get; set; }
    
        public virtual tb_payment tb_payment { get; set; }
    }
}
