//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AceTuitionPaymentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_payment()
        {
            this.tb_payment_file = new HashSet<tb_payment_file>();
            this.tb_receipt = new HashSet<tb_receipt>();
        }
    
        public int payment_id { get; set; }
        public System.DateTime payment_date { get; set; }
        public System.DateTime payment_upload_date { get; set; }
        public string payment_status { get; set; }
        public decimal payment_amount { get; set; }
        public int payment_month { get; set; }
        public int payment_year { get; set; }
        public decimal payment_outstanding { get; set; }
        public string parent_ic { get; set; }
        public string admin_ic { get; set; }
        public string child_ic { get; set; }
        public Nullable<System.DateTime> payment_decision_date { get; set; }
        public Nullable<decimal> payment_balance_amount { get; set; }
    
        public virtual tb_admin tb_admin { get; set; }
        public virtual tb_parent tb_parent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_payment_file> tb_payment_file { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_receipt> tb_receipt { get; set; }
    }
}
