//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AceTuitionPaymentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_receipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_receipt()
        {
            this.tb_receipt_addon = new HashSet<tb_receipt_addon>();
            this.tb_receipt_discount = new HashSet<tb_receipt_discount>();
            this.tb_receipt_package = new HashSet<tb_receipt_package>();
        }
    
        public int receipt_id { get; set; }
        public int payment_id { get; set; }
        public string child_ic { get; set; }
        public decimal receipt_outstanding { get; set; }
        public string receipt_status { get; set; }
        public int early_id { get; set; }
        public string receipt_code { get; set; }
    
        public virtual tb_child tb_child { get; set; }
        public virtual tb_early_payment tb_early_payment { get; set; }
        public virtual tb_payment tb_payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_receipt_addon> tb_receipt_addon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_receipt_discount> tb_receipt_discount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_receipt_package> tb_receipt_package { get; set; }
    }
}
